### ISSUE TITLE
DeviceCheck macOS

### ISSUE THREAD

**Issue by aehlke** [ronaldmannak/SwiftOpenAIProxy#6]
You mention that app attention isn't available in macOS. However from the docs it looks like it is, eg https://developer.apple.com/documentation/devicecheck/dcappattestservice says macOS 11 is supported. Am I missing something? It would be great to have this. Thanks

**Comment by mattcorey** [comment]
Despite the API's being available on macOS, `isSupported` always returns false:  https://developer.apple.com/documentation/devicecheck/dcappattestservice/issupported

**Comment by aehlke** [comment]
Thanks for clarifying that
